---
version: '2'
# Configuration of the Cycloid stack
name: 'Monitoring'
canonical: 'stack-monitoring'
status: 'private'
description: |
  Deploy a monitoring solution based on Alertmanager, Grafana and Prometheus.
keywords:
  - 'prometheus'
  - 'grafana'
  - 'alertmanager'
  - 'monitoring'
  - 'alerting'
  - 'observability'
  - 'k8s'
  - 'kubernetes'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-prometheus/master/icon.png
technologies:
  - technology: grafana
    version: n/a
  - technology: alertmanager
    version: n/a
  - technology: prometheus
    version: n/a

config:
  # PROVIDER MANAGED MODE
  aws-managed:
    name: 'AWS Managed solution'
    description: 'Managed solution for monitoring using AWS Managed Services'
    pipeline:
      pipeline:
        path: 'pipeline/provider-managed-mode/aws/pipeline.yml'
      variables:
        path: 'pipeline/provider-managed-mode/aws/variables.sample.yml'
        destination: '($ project $)/pipeline/aws-managed/variables-($ environment $).yml'
    terraform:
      prometheus:
        path: 'terraform/provider-managed-mode/aws/monitoring.tf.sample'
        destination: '($ project $)/terraform/aws-managed/($ environment $)/monitoring.tf'
#  azure-managed:
#  gcp-managed:

  # VM MODE
  azure-vm:
    name: 'Azure VM solution'
    description: 'Deploys monitoring solutions as local containers in VM'
    pipeline:
      pipeline:
        path: 'pipeline/vm-mode/azure/pipeline.yml'
      variables:
        path: 'pipeline/vm-mode/azure/variables.sample.yml'
        destination: '($ project $)/pipeline/azure-vm/variables-($ environment $).yml'
    terraform:
      azure-vm:
        path: 'terraform/vm-mode/azure/monitoring.tf.sample'
        destination: '($ project $)/terraform/azure-vm/($ environment $)/monitoring.tf'
    ansible:
      azure-vm:
        path: 'ansible/environments/env_azure_monitoring.yml'
        destination: '($ project $)/ansible/environments/($ environment $)_azure_monitoring.yml'

  aws-vm:
    name: 'AWS VM solution'
    description: 'Deploys monitoring solutions as local containers in EC2'
    pipeline:
      pipeline:
        path: 'pipeline/vm-mode/aws/pipeline.yml'
      variables:
        path: 'pipeline/vm-mode/aws/variables.sample.yml'
        destination: '($ project $)/pipeline/aws-vm/variables-($ environment $).yml'
    terraform:
      aws-vm:
        path: 'terraform/vm-mode/aws/monitoring.tf.sample'
        destination: '($ project $)/terraform/aws-vm/($ environment $)/monitoring.tf'
    ansible:
      aws-vm:
        path: 'ansible/environments/env_aws_monitoring.yml'
        destination: '($ project $)/ansible/environments/($ environment $)_aws_monitoring.yml'

#  gcp-vm:

# K8S PROMETHEUS STACK MODE
#  aws-k8s-stack:
#  azure-k8s-stack:
#  gcp-k8s-stack:

