{
 "title": "Concourse Metrics Status",
 "tags": [
  "cycloid.io",
  "concourse"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(concourse_db_queries_total, namespace)"
    }
   },
   {
    "name": "time_interval",
    "label": "time interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Concourse Web Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod concourse web health (group: $time_interval)",
     "type": "heatmap",
     "description": "if this is RED, it means at least one component is unhealthy (e.g. failing worker). it does not imply concourse is down.\n\nthis graph uses bosh health to determine if the cluster is healthy. this is not perfect, as bosh primarily just ensures the cluster components are running, not if they are in a good state.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "min(min_over_time(kube_pod_container_status_ready{pod=~\"concourse-web-.+\", namespace=~\"$namespace\"}[$__interval])) by (pod)",
       "legendFormat": "pod: {{ pod }}"
      },
      {
       "expr": "min(min_over_time(probe_success{product=\"concourse\", namespace=~\"$namespace\"}[$__interval])) by (instance)",
       "legendFormat": "probe: {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nr of Containers and Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster container per worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  concourse_workers_containers{namespace=~\"$namespace\"}\n) by (namespace, worker)",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Cluster container total count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(concourse_workers_containers{namespace=~\"$namespace\"}) by (namespace, cluster)",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Jobs scheduled (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_jobs_scheduled_total{namespace=~\"$namespace\"}[$__interval])) by (namespace, cluster)",
       "legendFormat": "{{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipelines Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 run durations per pipeline (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(\r5,\r\n    sort_desc(\r\n        sum(\r\n            increase(\rconcourse_builds_duration_seconds_sum{namespace=~\"$namespace\"}[30m]\r)\n        \r) by (\n            namespace, team, pipeline\n        )\n\r    )\r\n\r)",
       "legendFormat": "{{ namespace }}/{{ team }}/{{ pipeline }}"
      }
     ]
    },
    {
     "title": "Nr of Failed Pipelines (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_builds_failed_total{namespace=~\"$namespace\"}[$__interval])) by (namespace, cluster)",
       "legendFormat": "{{ cluster }}"
      },
      {
       "expr": "sum(increase(concourse_builds_failed_total{namespace=~\"$namespace\"}[$__interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Nr of errored pipelines - concourse errors (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_builds_errored_total{namespace=~\"$namespace\"}[$__interval])) by (namespace, cluster)",
       "legendFormat": "{{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Concourse Resource Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource checks (started/finished/errored every 1h)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_lidar_checks_finished_total{namespace=~\"$namespace\", status=\"error\"}[$__interval])) by (pod) / sum(increase(concourse_lidar_checks_started_total{namespace=~\"$namespace\"}[$__interval])) by (pod)",
       "legendFormat": "errored: {{ pod }}"
      },
      {
       "expr": "sum(increase(concourse_lidar_checks_finished_total{namespace=~\"$namespace\", status=\"error\"}[$__interval])) / sum(increase(concourse_lidar_checks_started_total{namespace=~\"$namespace\"}[$__interval]))",
       "legendFormat": "all clusters avg"
      },
      {
       "expr": "sum(increase(concourse_lidar_checks_finished_total{namespace=~\"$namespace\", status=\"error\"}[$__interval] offset 7d)) / sum(increase(concourse_lidar_checks_started_total{namespace=~\"$namespace\"}[$__interval] offset 7d))",
       "legendFormat": "all clusters avg: -1w"
      }
     ]
    },
    {
     "title": "Nr of resource checks status (started/finished/errored) (every $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_lidar_checks_started_total{namespace=~\"$namespace\"}[$__interval])) by (namespace, pod)",
       "legendFormat": "started: {{ pod }}"
      },
      {
       "expr": "sum(increase(concourse_lidar_checks_finished_total{namespace=~\"$namespace\", status=\"success\"}[$__interval])) by (namespace, pod)",
       "legendFormat": "finished: {{ pod }}"
      },
      {
       "expr": "sum(increase(concourse_lidar_checks_finished_total{namespace=~\"$namespace\", status=\"error\"}[$__interval])) by (namespace, pod)",
       "legendFormat": "errored: {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Concourse Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database queries per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(concourse_db_queries_total{namespace=~\"$namespace\"}[$__interval])) by (pod) / 300",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Database connections (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_db_connections{namespace=~\"$namespace\"}[$__interval])) by (pod, dbname)",
       "legendFormat": "{{ pod }}/{{ dbname }}"
      }
     ]
    },
    {
     "title": "Database locks held (per $time_interval)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(concourse_locks_held{namespace=~\"$namespace\"}[$__interval])) by (pod, type)",
       "legendFormat": "{{ pod }}/{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 30 Finished pipeline builds",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "topk(30, sort_desc(sum(concourse_builds_finished{namespace=~\"$namespace\"}) by (pipeline)))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "Top 10 Concourse Errors (per 5m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(increase(concourse_error_logs{namespace=~\"$namespace\"}[$__interval])) by (cluster, message)) > 0",
       "legendFormat": "{{ cluster }}/{{ message }}"
      }
     ]
    }
   ]
  }
 ]
}