{
 "title": "cycloid > Product usage (Beta)",
 "description": "Based on Gael export to be added in backend",
 "tags": [ "cycloid.io" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(youdeploy_mysql_exporter_members, namespace)"
    }
   },
   {
    "name": "organization",
    "label": "Org",
    "query": {
     "query": "label_values(youdeploy_mysql_exporter_members{namespace=\"$namespace\"}, organization)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(youdeploy_mysql_exporter_members{namespace=\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Youdeploy overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (youdeploy_mysql_exporter_uniqusers{namespace=\"$namespace\", cycloid_user=\"false\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(youdeploy_mysql_exporter_members{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (youdeploy_mysql_exporter_projects{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Deployed Stacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(youdeploy_mysql_exporter_pipelines{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Credentials",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(youdeploy_mysql_exporter_credentials{namespace=\"$namespace\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Avg envs per Projects",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum by (project,organization) (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Deployed public stacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", type=\"public\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unpayed orgs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(youdeploy_mysql_exporter_members{namespace=\"$namespace\", organization!~\"cycloid.*\", blocked=\"require_payment\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Expected monthly bill in €",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (youdeploy_mysql_exporter_members{namespace=\"$namespace\", organization!~\"cycloid.*\", blocked!=\"require_payment\", instance=\"$instance\"}) * 45"
    }
   ]
  },
  {
   "title": "Overall totals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(youdeploy_mysql_exporter_members{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "organizations"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_credentials{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "credentials"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_roles{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "roles"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_pipelines{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "pipelines"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_teams{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "teams"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_service_catalogs_sources{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "service catalogs"
    },
    {
     "expr": "count (youdeploy_mysql_exporter_service_catalogs_sources{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "service catalogs sources"
    },
    {
     "expr": "sum (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "Deployed stacks (envs)"
    },
    {
     "expr": "sum (youdeploy_mysql_exporter_projects{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "Projects"
    },
    {
     "expr": "youdeploy_mysql_exporter_uniqusers{namespace=\"$namespace\", cycloid_user=\"false\", instance=\"$instance\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "avg (sum by (project,organization) (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"}))",
     "legendFormat": "Avg environments per projects"
    }
   ]
  },
  {
   "title": "Total Organizations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (blocked) (youdeploy_mysql_exporter_members{namespace=\"$namespace\", organization!~\"cycloid.*\", instance=\"$instance\"})",
     "legendFormat": "{{ blocked }}"
    },
    {
     "expr": "count(youdeploy_mysql_exporter_members{namespace=\"$namespace\", organization=~\"cycloid.*\", instance=\"$instance\"})",
     "legendFormat": "Cycloid"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "youdeploy_mysql_exporter_uniqusers{namespace=\"$namespace\", cycloid_user=\"false\", instance=\"$instance\"}",
     "legendFormat": "Standard users"
    },
    {
     "expr": "youdeploy_mysql_exporter_uniqusers{namespace=\"$namespace\", cycloid_user=\"true\", instance=\"$instance\"}",
     "legendFormat": "Cyloid users"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_orphanusers{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "orphan users"
    },
    {
     "expr": "sum(youdeploy_mysql_exporter_uniqusers{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total credentials",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (youdeploy_mysql_exporter_credentials{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum (youdeploy_mysql_exporter_credentials{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total deployed stacks (sum of envs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Stacks per type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (youdeploy_mysql_exporter_service_catalogs_sources{namespace=\"$namespace\", instance=\"$instance\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total deployed public stacks (sum of envs) per stack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_catalog) (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", type=\"public\", instance=\"$instance\"})",
     "legendFormat": "{{service_catalog}}"
    }
   ]
  },
  {
   "title": "Youdeploy per organization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Members",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "youdeploy_mysql_exporter_members{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"}",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Credentials",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (organization) (youdeploy_mysql_exporter_credentials{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"})",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "youdeploy_mysql_exporter_roles{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"}",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "youdeploy_mysql_exporter_pipelines{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"}",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Teams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "youdeploy_mysql_exporter_teams{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"}",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (organization) (youdeploy_mysql_exporter_service_catalogs_sources{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"})",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (organization) (youdeploy_mysql_exporter_projects{namespace=\"$namespace\", organization=~\"$organization\", service_catalog!=\"none\", instance=\"$instance\", instance=\"$instance\"})",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Orphan Projects (no stack deployed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (organization) (youdeploy_mysql_exporter_projects{namespace=\"$namespace\", organization=~\"$organization\", service_catalog=\"none\", instance=\"$instance\"})",
     "legendFormat": "{{organization}}"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (organization) (youdeploy_mysql_exporter_service_catalogs{namespace=\"$namespace\", organization=~\"$organization\", instance=\"$instance\"})",
     "legendFormat": "{{organization}}"
    }
   ]
  }
 ]
}