{
 "title": "Cycloid Service Status",
 "tags": [ "cycloid.io" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "label": "env",
    "query": {
     "query": "label_values(health_status_concourse,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concourse status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_concourse{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ElasticSearch status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_elasticsearch{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_email{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_mysql{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_redis{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Worker status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_redis_worker{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_status_vault{job=\"cycloid-health-check\", env=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "All Services",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "health_status_concourse{env=\"$Environment\"}",
     "legendFormat": "Concourse"
    },
    {
     "expr": "health_status_elasticsearch{env=\"$Environment\"}",
     "legendFormat": "ElasticSearch"
    },
    {
     "expr": "health_status_email{env=\"$Environment\"}",
     "legendFormat": "Email"
    },
    {
     "expr": "health_status_mysql{env=\"$Environment\"}",
     "legendFormat": "MySQL"
    },
    {
     "expr": "health_status_redis{env=\"$Environment\"}",
     "legendFormat": "Redis"
    },
    {
     "expr": "health_status_redis_worker{env=\"$Environment\"}",
     "legendFormat": "Redis Worker"
    }
   ]
  }
 ]
}