{
 "title": "Cycloid API Status",
 "tags": [ "cycloid.io" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cycloidio_http_request_duration_sum, namespace)"
    }
   },
   { "name": "latency", "query": "0,100,200,500,1000" }
  ]
 },
 "panels": [
  {
   "title": "Cycloid IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(cycloidio_http_request_duration_sum{namespace=\"$namespace\"}[2m])) by (action_name) / avg(rate(cycloidio_http_request_duration_count{namespace=\"$namespace\"}[2m])) by (action_name) > $latency",
     "legendFormat": "{{action_name}}"
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(cycloidio_http_request_duration_count{namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Requests by actions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action_name) (rate(cycloidio_http_request_duration_count{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "{{action_name}}"
    }
   ]
  }
 ]
}