---
#
# Install in AWS VM
#
- hosts: tag_vm_aws
  become: yes
  ignore_unreachable: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - ["environments/{{env}}_aws_vm_monitoring.yml","environments/empty.yml"]
    - "environments/default_vm_monitoring.yml"

  tasks:
    - name: Setup AWS VM
      ansible.builtin.include_tasks:
        file: vm-setup.yml

#
# Install in Azure VM
#
# TODO to find another way to integrate the other 2 usecases when host group is empty
#- hosts: tag_vm_azure
#  become: yes
#  ignore_unreachable: true
#
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
#
#  vars_files:
#    - ["environments/{{env}}_azure_vm_monitoring.yml","environments/empty.yml"]
#    - "environments/default_vm_monitoring.yml"
#
#  tasks:
#    - name: Setup Azure VM
#      ansible.builtin.include_tasks:
#        file: vm-setup.yml
