---

#
# Prometheus
#
- hosts: tag_vm_monitoring_azure
  become: yes
  serial: 50%

  vars_files:
    - "environments/default_azure_monitoring.yml"
    - "environments/{{env}}_azure_monitoring.yml"

  pre_tasks:
  # TODO only if create grafana creation enabled
  # only execute one
  # Mount volume mysql in instance
    - name: Get device name to use
      set_fact:
        device_name: "/dev/{{item}}"
      when: ansible_facts.devices.{{item}}.partitions == {}
      with_items: "{{ ansible_facts.devices}}"

    - name: Create partition on data disk
      parted:
        device: "{{device_name}}"
        number: 1
        state: present

    - name: Create a ext4 fs on data disk
      filesystem:
        fstype: ext4
        dev: "{{device_name}}1"

    - name: Get UUID for partition
      command: blkid -s UUID -o value "{{device_name}}1"
      register: disk_blkid

    - name: Create disk mount point
      file:
        state: directory
        path: /mysql-grafana
        mode: 0777

    - name: Mount data disk
      mount:
        path: "/mysql-grafana"
        src: "UUID={{disk_blkid.stdout}}"
        fstype: ext4
        state: mounted

  roles:
    # Install docker
    - role: geerlingguy.docker
      docker_packages:
        - "docker-{{ docker_edition }}"
        - "docker-{{ docker_edition }}-cli"
        - "containerd.io"
      tags:
        - docker
  # TODO only if create grafana creation enabled
    # Install mysql - grafana database
    - role: geerlingguy.mysql
      mysql_datadir: "/mysql-grafana"
      mysql_root_password: ""
      mysql_databases:
        - name: "{{grafana_database_name}}"
          enconding:
          collation:
      mysql_users:
        - name: "{{grafana_admin_user}}"
          password: "{{grafana_admin_password}}"
          priv: '*.*:ALL'
          host: '%'
      tags:
        - mysql

    # Install prometheus, alertmanager and grafana
    - role: cycloid.prometheus
      path: /opt/prometheus
      tags:
        - prometheus

    # Monitoring client part
    - role: cycloid.telegraf
      tags:
        - telegraf

    # Install nginx
    - role: jdauphant.nginx
      tags:
        - nginx
