---
  # Install NGINX
  # Install SSL certificates for nginx
  - name: "Create SSL directory"
    file:
      path: "{{ certificates_dest }}"
      state: directory
    when: use_ssl | bool
    tags: nginx

  - name: "Install SSL certificates"
    copy:
      src: "{{ item }}"
      dest: "{{ certificates_dest }}"
      mode: 0600
    with_fileglob:
      - "{{ certificates_src }}"
    when: use_ssl | bool and not create_self_signed_certificate | bool
    tags: nginx

  - name: "Install self signed certificate"
    block:
      - name: "Create private key"
        openssl_privatekey:
          path: "{{ certificates_dest }}/tls.key"
          size: 2048

      - name: "Create signing request"
        openssl_csr:
          path: "{{ certificates_dest }}/tls.csr"
          privatekey_path: "{{ certificates_dest }}/tls.key"

      - name: "Create signing request"
        openssl_certificate:
          path: "{{ certificates_dest }}/tls.crt"
          csr_path: "{{ certificates_dest }}/tls.csr"
          privatekey_path: "{{ certificates_dest }}/tls.key"
          provider: selfsigned
    when: use_ssl | bool and create_self_signed_certificate | bool
    tags: nginx

  - name: Install NGINX
    include_role:
      name: jdauphant.nginx
    tags: nginx

  # Install Prometheus
  - name: Install Prometheus
    include_role:
      name: prometheus.prometheus.prometheus
    tags: prometheus

  - name: "Create custom alert rule file"
    template:
      src: templates/customer.rules
      dest: "{{ prometheus_config_dir }}/rules/{{customer}}.rules"
    when: prometheus_skip_install | bool and prometheus_custom_rules != ""
    tags: prometheus

  # Install Alertmanager
  - name: Install Alertmanager
    include_role:
      name: prometheus.prometheus.alertmanager
    tags: alertmanager

    # Install exporters
  - name: Install Blackbox exporter
    include_role:
      name: prometheus.prometheus.blackbox_exporter
    tags: blackbox_exporter


  - name: Install MYSQL exporter
    include_role:
      name: prometheus.prometheus.mysqld_exporter
    tags: mysqld_exporter

  - name: Install PostgreSQL exporter
    include_role:
      name: prometheus.prometheus.postgres_exporter
    tags: postgres_exporter

  - name: Install Node exporter
    include_role:
      name: prometheus.prometheus.node_exporter
    tags: node_exporter

  - name: Install Process exporter
    include_role:
      name: prometheus.prometheus.process_exporter
    tags: process_exporter

  - name: Install Systemd exporter
    include_role:
      name: prometheus.prometheus.systemd_exporter
    tags: systemd_exporter

  # Install Grafana
  - name: Install Grafana
    include_role:
      name: grafana.grafana.grafana
    when: not grafana_skip_install
    tags: grafana

  - name: Copy stack grafana dashboards JSON files to the target directory
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ grafana_data_dir }}/{{ grafana_dashboards_dir }}"
    with_fileglob:
      - "{{ grafana_dashboards_files}}"
    mode: '0644'
    when: not grafana_skip_install
    tags: grafana
