---
  - name: Update apt cache (equivalent to apt-get update)
    apt:
      update_cache: yes

  # Install Prometheus
  - name: Install Prometheus
    include_role:
      name: prometheus.prometheus.prometheus
    tags: prometheus
    when: prometheus_install

  - name: "Create custom alert rule file"
    template:
      src: templates/organization.rules
      dest: "{{ prometheus_config_dir }}/rules/{{organization}}.rules"
    when: prometheus_install | bool and prometheus_custom_rules != ""
    tags: prometheus

  # Install Alertmanager
  - name: Install Alertmanager
    include_role:
      name: prometheus.prometheus.alertmanager
    tags: alertmanager
    when: alertmanager_install

    # Install exporters
  - name: Install Blackbox exporter
    include_role:
      name: prometheus.prometheus.blackbox_exporter
    tags: blackbox_exporter
    when: blackbox_exporter_install

  - name: Install MYSQL exporter
    include_role:
      name: prometheus.prometheus.mysqld_exporter
    tags: mysqld_exporter
    when: mysqld_exporter_install

  - name: Install PostgreSQL exporter
    include_role:
      name: prometheus.prometheus.postgres_exporter
    tags: postgres_exporter
    when: postgres_exporter_install

  - name: Install Node exporter
    include_role:
      name: prometheus.prometheus.node_exporter
    tags: node_exporter
    when: node_exporter_install

 # Install Grafana
  - name: Install Grafana
    include_role:
      name: grafana.grafana.grafana
    when: grafana_install
    tags: grafana

  - name: Copy stack grafana dashboards JSON files to the target directory
    copy:
      src: "{{ item }}"
      dest: "{{ grafana_data_dir }}/{{ grafana_dashboards_dir }}"
      mode: '0644'
    with_fileglob:
      - "{{ grafana_dashboards_files}}"
    when: grafana_install
    tags: grafana

  # Install NGINX
  # Install SSL certificates for nginx
  - name: "Create SSL directory"
    file:
      path: "{{ certificates_dest }}"
      state: directory
    when: use_ssl | bool
    tags: nginx

  - name: "Install SSL certificates"
    copy:
      src: "{{ item }}"
      dest: "{{ certificates_dest }}"
      mode: 0600
    with_fileglob:
      - "{{ certificates_src }}"
    when: use_ssl | bool and not create_self_signed_certificate | bool
    tags: nginx

  - name: "Install self signed certificate"
    block:
      - name: "Create private key"
        openssl_privatekey:
          path: "{{ certificates_dest }}/tls.key"
          size: 2048

      - name: "Create signing request"
        openssl_csr:
          path: "{{ certificates_dest }}/tls.csr"
          privatekey_path: "{{ certificates_dest }}/tls.key"

      - name: "Create signing request"
        openssl_certificate:
          path: "{{ certificates_dest }}/tls.crt"
          csr_path: "{{ certificates_dest }}/tls.csr"
          privatekey_path: "{{ certificates_dest }}/tls.key"
          provider: selfsigned
    when: use_ssl | bool and create_self_signed_certificate | bool
    tags: nginx

  - name: Install NGINX
    include_role:
      name: jdauphant.nginx
    tags: nginx